#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Tue Jan 22 15:06:05 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class Panchanga(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Panchanga.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_2 = wx.StaticText(self, -1, "Hindu Drik Panchanga ")
        self.label_3 = wx.StaticText(self, -1, "Gregorian Date")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "2013")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Panchanga.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Panchanga.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(6, 3, 0, 0)
        label_1 = wx.StaticText(self, -1, "")
        grid_sizer_1.Add(label_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        label_4 = wx.StaticText(self, -1, "")
        grid_sizer_1.Add(label_4, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        label_5 = wx.StaticText(self, -1, "")
        grid_sizer_1.Add(label_5, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Panchanga
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Panchanga(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
